---
title: Aioxx Blog
email: hello@sobkiso.xyz
description: A Blog by Nullbite
author: Nullbite
baseurl: /
url: https://aioxx.github.io
twitter_username: cyberxbd
github_username: cyberxbd
facebook_username: cyberxbd
instagram_username: cyberxbd
linkedin_username: cyberxbd

google_analytics: G-YYJHZGS99C

markdown: kramdown
paginate: 7
paginate_path: /posts/page:num/
plugins:
  - jekyll-workbox-plugin
  - jekyll-loading-lazy
  - jekyll-youtube
  - jekyll-pdf-embed
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist

workbox:
  sw_src_filepath: sw.js
  sw_dest_filename: sw.js
  precache_recent_posts_num: 7
  precache_glob_directory: /
  precache_glob_patterns:
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
    - about.html
    - about
    - contact
  precache_glob_ignores:
    - fonts/**/*


